// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `crabbox` plugin's OWN CUE schema — the typed plugin_input for the
// `crabbox` check verb, which probes the Crabbox CLI and its optional local
// coordinator.
//
// SELF-CONTAINED by contract: it references NO base def, so it compiles standalone
// (both `cue exp gengotypes` and the host's load-gate compile) AND splices onto the
// base as `base ++ plugin`.
type CrabboxInput struct {
	// method — the operation (also the scalar-sugar primary, so `crabbox: version`
	// desugars to {method: "version"}).
	Method string `json:"method"`

	// port — the coordinator port to probe for health/ready. Default 8080 (the
	// crabbox-coordinator candy's published port).
	Port int `json:"port"`

	// timeout — the HTTP probe timeout. Default 10s.
	Timeout string `json:"timeout"`

	// json_path — a dotted path into the JSON response; when set, the verb's stdout
	// is the value at that path rather than the whole document.
	JSONPath string `json:"json_path"`

	// run_id — run identifier required by the events/logs methods.
	RunID string `json:"run_id"`
}
